---
- hosts: localhost
  connection: local

  pre_tasks:
  - set_fact:
     username: "{{ lookup('pipe', 'whoami') }}"
    tags:
    - always

  roles:
  - tools
  - devel
  - desktop
  - network
  - libvirt
